import { BrowserMultiFormatReader } from "@zxing/browser";
import { Clipboard } from "@capacitor/clipboard";
let installed=false;let activeOverlay:HTMLElement|null=null;let activeStop:(()=>void)|null=null;
function setValue(input:HTMLInputElement|HTMLTextAreaElement,value:string){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input),"value")?.set;if(setter)setter.call(input,value);else input.value=value;input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));input.focus()}
function findNearby(button:HTMLElement){let p:HTMLElement|null=button;for(let i=0;i<5&&p;i++,p=p.parentElement){const input=p.querySelector("input:not([type='hidden']),textarea") as HTMLInputElement|HTMLTextAreaElement|null;if(input)return input}return document.querySelector("input:focus,textarea:focus") as HTMLInputElement|HTMLTextAreaElement|null}
async function clipboard(){try{const r=await Clipboard.read();if(r.value?.trim())return r.value.trim()}catch{}try{return (await navigator.clipboard?.readText())?.trim()||""}catch{return ""}}
function toast(s:string){document.getElementById("anp-device-toast")?.remove();const e=document.createElement("div");e.id="anp-device-toast";e.textContent=s;e.dir="rtl";e.style.cssText="position:fixed;left:50%;bottom:110px;transform:translateX(-50%);z-index:100006;background:rgba(2,19,28,.97);color:#fff;border:1px solid rgba(0,214,176,.45);border-radius:14px;padding:11px 17px;font:700 12px Vazirmatn,sans-serif";document.body.appendChild(e);setTimeout(()=>e.remove(),1600)}
async function paste(button:HTMLElement){const input=findNearby(button);if(!input){toast("فیلد مقصد پیدا نشد");return}const value=await clipboard();if(!value){toast("متنی برای چسباندن در کلیپ‌بورد نیست");return}const meta=`${input.getAttribute("aria-label")||""} ${input.getAttribute("placeholder")||""}`;const numeric=/کد|otp|authenticator|رمز|پویا/i.test(meta);const out=numeric?value.replace(/\D/g,"").slice(0,6):value;if(!out){toast("مقدار مناسب برای این فیلد در کلیپ‌بورد نیست");return}setValue(input,out);const old=button.textContent||"چسباندن";button.textContent="✓ چسبانده شد";setTimeout(()=>{if(button.isConnected)button.textContent=old},1100)}
function closeScanner(){activeStop?.();activeStop=null;activeOverlay?.remove();activeOverlay=null}
function scanner(button:HTMLElement){closeScanner();const target=findNearby(button);if(!target){toast("فیلد آدرس مقصد پیدا نشد");return}const overlay=document.createElement("div");overlay.dir="rtl";overlay.style.cssText="position:fixed;inset:0;z-index:100004;background:#020e18;color:#fff;font-family:Vazirmatn,sans-serif;display:flex;flex-direction:column;align-items:center;overflow:hidden";overlay.innerHTML=`<header style="width:100%;box-sizing:border-box;padding:calc(env(safe-area-inset-top,0px) + 14px) 16px 12px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid rgba(0,214,176,.12)"><button data-close style="border:0;border-radius:12px;padding:9px 15px;background:rgba(255,255,255,.08);color:#fff;font:700 13px Vazirmatn">بستن</button><b>آن پرداز</b><span style="width:55px"></span></header><div style="margin-top:30px;text-align:center"><strong style="font-size:19px">اسکن آدرس ارز دیجیتال</strong><p style="font-size:12px;color:#8fa2ad;margin-top:7px">آدرس کیف پول مقصد را روبروی دوربین قرار دهید</p></div><div style="position:relative;width:min(82vw,340px);aspect-ratio:1;margin-top:26px;border:2px solid #00d6b0;border-radius:26px;overflow:hidden;background:#000;box-shadow:0 0 45px rgba(0,214,176,.18)"><video data-video autoplay playsinline muted style="width:100%;height:100%;object-fit:cover;display:block"></video><div style="position:absolute;inset:24px;border:2px solid rgba(0,214,176,.85);border-radius:18px;pointer-events:none"></div><div style="position:absolute;left:12%;right:12%;top:50%;height:2px;background:#00d6b0;box-shadow:0 0 12px #00d6b0"></div></div><p data-status style="font-size:12px;color:#8fa2ad;margin:20px 24px;text-align:center">در حال فعال‌سازی دوربین...</p>`;document.body.appendChild(overlay);activeOverlay=overlay;overlay.querySelector<HTMLButtonElement>("[data-close]")!.onclick=closeScanner;const video=overlay.querySelector<HTMLVideoElement>("[data-video]")!;const status=overlay.querySelector<HTMLElement>("[data-status]")!;const reader=new BrowserMultiFormatReader();let done=false;reader.decodeFromConstraints({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}}},video,(result)=>{if(done||!result)return;const raw=result.getText().trim();if(raw.length<8){status.textContent="کد شناسایی شد اما معتبر نیست.";return}done=true;setValue(target,raw.replace(/^(bitcoin|ethereum|tron|bnb|litecoin):?/i,"").split("?")[0]);status.textContent="آدرس مقصد با موفقیت شناسایی شد";toast("آدرس مقصد وارد شد");setTimeout(closeScanner,450)}).then(c=>{activeStop=()=>c.stop();status.textContent="دوربین فعال است؛ کد را داخل کادر قرار دهید."}).catch(()=>{status.textContent="دسترسی به دوربین ممکن نشد؛ مجوز دوربین را فعال کنید."})}
export function installExchangeDeviceFixes(){if(installed)return;installed=true;document.addEventListener("click",e=>{const button=(e.target as HTMLElement|null)?.closest("button") as HTMLButtonElement|null;if(!button)return;const t=(button.innerText||button.textContent||"").trim();if(t.includes("چسباندن")){e.preventDefault();e.stopImmediatePropagation();void paste(button);return}if(/اسکن/i.test(t)){e.preventDefault();e.stopImmediatePropagation();scanner(button)}},true)}
