import { useMemo, useState } from "react";
import { buildFinancialInsight, type IncomeMode, type IncomeSource, type IncomeType, type ExpenseItem } from "./financialInsights";
const TYPES:Record<IncomeType,string>={salary:"حقوق",job1:"شغل ۱",job2:"شغل ۲",business:"کسب‌وکار",rent:"اجاره",other:"سایر"};
const MODES:Record<IncomeMode,string>={fixed:"ثابت",variable:"متغیر",approximate:"تقریبی"};
const IK="anp_income_sources_v1", CK="anp_expense_category_learning_v1";
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n));
const load=(k:string,d:any)=>{try{return JSON.parse(localStorage.getItem(k)||"")??d}catch{return d}};
function category(x:any,l:Record<string,string>){const k=String(x.merchant||x.payee||x.note||"").trim();if(k&&l[k])return l[k];if(x.type==="service")return "خدمات و قبوض";if(x.type==="transfer")return "انتقال وجه";if(x.type==="swap")return "تبدیل دارایی";if(x.source==="exchange")return "صرافی";return "متفرقه";}
export default function FinancialCenterV2({onClose}:{onClose:()=>void}){
 const [income,setIncome]=useState<IncomeSource[]>(()=>load(IK,[]));const [learned,setLearned]=useState<Record<string,string>>(()=>load(CK,{}));const [adding,setAdding]=useState(false);
 const [draft,setDraft]=useState<IncomeSource>({id:`i-${Date.now()}`,type:"salary",title:"",amount:0,mode:"fixed",active:true});const phone=localStorage.getItem("anp_current")||"";
 const expenses=useMemo<ExpenseItem[]>(()=>{const tx=load(`anp_tx_${phone}`,[]);return (Array.isArray(tx)?tx:[]).filter((x:any)=>x.status!=="failed"&&x.type!=="deposit").map((x:any,i:number)=>({id:String(x.id||i),amount:Number(x.convertedAmount??x.amount)||0,date:String(x.createdAt||new Date().toISOString()),category:category(x,learned),merchant:String(x.merchant||x.payee||x.note||"") ,source:x.source==="exchange"?"exchange":x.type==="service"?"bill":x.type==="transfer"?"transfer":x.source==="pos"?"pos":"other"}));},[phone,learned]);
 const insight=useMemo(()=>buildFinancialInsight(income,expenses),[income,expenses]);
 const saveIncome=()=>{if(!draft.title.trim())return;const next=[...income,{...draft,title:draft.title.trim(),amount:Number(draft.amount)||0,active:true}];setIncome(next);localStorage.setItem(IK,JSON.stringify(next));setAdding(false);setDraft({id:`i-${Date.now()}`,type:"salary",title:"",amount:0,mode:"fixed",active:true});};
 const learn=(x:ExpenseItem,v:string)=>{const k=x.merchant||x.category;const n={...learned,[k]:v};setLearned(n);localStorage.setItem(CK,JSON.stringify(n));};
 const status=insight.status==="normal"?"عادی":insight.status==="needs-attention"?"نیازمند توجه":"هشدار مالی";
 return <div className="anp-f2" dir="rtl"><header><button onClick={onClose} aria-label="بازگشت">‹</button><div><b>مرکز مالی</b><span>نمایش ساده و کاربردی وضعیت مالی</span></div></header><main>
 <section className={`f2-hero ${insight.status}`}><div><small>وضعیت مالی</small><strong>{status}</strong></div><div><small>هزینه / درآمد</small><strong>{fa(insight.expenseRatio*100)}٪</strong></div></section>
 <section className="f2-grid"><div><small>درآمد</small><b>{fa(insight.monthlyIncome)}</b><em>ریال / ماه</em></div><div><small>هزینه</small><b>{fa(insight.monthlyExpense)}</b><em>ریال / ماه</em></div><div><small>مانده</small><b>{fa(insight.balance)}</b><em>ریال</em></div><div><small>پس‌انداز</small><b>{fa(insight.savingsRate*100)}٪</b><em>نرخ</em></div></section>
 <section className="f2-card"><div className="f2-title"><div><b>درآمدها</b><span>منابع درآمدی شما</span></div><button onClick={()=>setAdding(true)}>＋ افزودن</button></div>{income.length?income.map(x=><div className="f2-row" key={x.id}><span>{x.title}<small>{TYPES[x.type]} · {MODES[x.mode]}</small></span><b>{fa(x.amount)} ریال</b></div>):<p>هنوز درآمدی ثبت نشده است.</p>}</section>
 <section className="f2-card"><div className="f2-title"><div><b>هزینه‌ها</b><span>بیشترین دسته‌های هزینه</span></div></div>{insight.topCategories.length?insight.topCategories.slice(0,5).map(x=><div className="f2-row" key={x.category}><span>{x.category||"متفرقه"}</span><b>{fa(x.amount)} ریال</b></div>):<p>با ثبت تراکنش‌ها، تحلیل هزینه خودکار تکمیل می‌شود.</p>}</section>
 <section className="f2-card"><div className="f2-title"><div><b>تحلیل هوشمند</b><span>{insight.expenseTrend==="up"?"روند هزینه‌ها افزایشی است.":insight.expenseTrend==="down"?"روند هزینه‌ها کاهشی است.":"روند هزینه‌ها پایدار است."}</span></div></div><div className="f2-insight">{insight.unusualExpenses.length?`⚠ ${insight.unusualExpenses.length} هزینه غیرعادی شناسایی شد.`:insight.recurringExpenses.length?`↻ ${insight.recurringExpenses.length} پرداخت تکرارشونده شناسایی شد.`:"✓ مورد غیرعادی قابل توجهی پیدا نشد."}</div></section>
 {expenses.some(x=>x.category==="متفرقه")&&<section className="f2-card"><div className="f2-title"><div><b>دسته‌بندی سریع</b><span>انتخاب شما برای دفعات بعد حفظ می‌شود</span></div></div>{expenses.filter(x=>x.category==="متفرقه").slice(0,4).map(x=><div className="f2-row" key={x.id}><span>{x.merchant||"تراکنش"}</span><select value={learned[x.merchant||x.category]||"متفرقه"} onChange={e=>learn(x,e.target.value)}><option>متفرقه</option><option>خوراک</option><option>خرید</option><option>حمل‌ونقل</option><option>قبوض</option><option>تفریح</option><option>سلامت</option><option>آموزش</option><option>سایر</option></select></div>)}</section>}
 </main>{adding&&<div className="f2-modal"><div><div className="f2-title"><b>افزودن درآمد</b><button onClick={()=>setAdding(false)}>×</button></div><label>نوع درآمد<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as IncomeType})}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>عنوان<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="مثلاً حقوق شرکت"/></label><label>مبلغ ماهانه<input inputMode="numeric" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:Number(e.target.value.replace(/\D/g,""))||0})}/></label><button className="f2-save" onClick={saveIncome}>ذخیره درآمد</button></div></div>}</div>;
}
