import { useMemo, useState } from "react";
import { deleteReminder, getReminders, requestReminderPermission, saveReminder, setReminderEnabled, type Reminder, type ReminderRepeat } from "./reminders";

const labels: Record<ReminderRepeat,string> = { once:"یک‌بار", daily:"روزانه", weekly:"هفتگی", monthly:"ماهانه", custom:"روزهای انتخابی" };
const days = ["ی","د","س","چ","پ","ج","ش"];
const make = (): Reminder => { const d=new Date(); return { id:`rem-${Date.now()}`, title:"", description:"", date:d.toISOString().slice(0,10), time:"09:00", repeat:"once", enabled:true, createdAt:d.toISOString() }; };

export default function ReminderPage({onClose}:{onClose:()=>void}) {
 const [items,setItems]=useState<Reminder[]>(getReminders()); const [edit,setEdit]=useState<Reminder|null>(null); const [error,setError]=useState("");
 const active=useMemo(()=>items.filter(x=>x.enabled).length,[items]);
 const refresh=()=>setItems(getReminders());
 const save=async()=>{ if(!edit?.title.trim()){setError("عنوان یادآور را وارد کنید.");return;} setError(""); const ok=await requestReminderPermission(); const next={...edit,title:edit.title.trim(),description:edit.description.trim()}; saveReminder(next); if(ok&&next.enabled) await setReminderEnabled(next.id,true); refresh(); setEdit(null); };
 return <div className="anp-reminders-page" dir="rtl">
  <header className="anp-reminders-header"><button className="back-btn" onClick={onClose}>‹</button><div><h2>یادآورها</h2><p>{active} فعال</p></div><button className="anp-reminders-add" onClick={()=>{setError("");setEdit(make())}}>+</button></header>
  <main className="anp-reminders-body">{items.length===0?<section className="anp-reminders-empty"><div className="anp-reminders-empty-icon">◷</div><h3>هنوز یادآوری ثبت نشده</h3><p>پرداخت‌ها و کارهای مهم مالی را برای زمان مناسب یادآوری کنید.</p><button className="primary-button" onClick={()=>setEdit(make())}>افزودن یادآور</button></section>:items.map(x=><article className={`anp-reminder-card${x.enabled?"":" is-disabled"}`} key={x.id}><div><div className="anp-reminder-title-row"><h3>{x.title}</h3><span>{labels[x.repeat]}</span></div>{x.description&&<p>{x.description}</p>}<div className="anp-reminder-meta"><span>{x.date}</span><b>{x.time}</b></div></div><div className="anp-reminder-actions"><button className={`anp-switch${x.enabled?" on":""}`} onClick={()=>void setReminderEnabled(x.id,!x.enabled).then(refresh)}><span/></button><button onClick={()=>setEdit(x)}>ویرایش</button><button className="danger" onClick={()=>void deleteReminder(x.id).then(refresh)}>حذف</button></div></article>)}</main>
  {edit&&<div className="anp-reminder-modal"><div className="anp-reminder-sheet"><div className="anp-reminder-sheet-head"><h3>{items.some(x=>x.id===edit.id)?"ویرایش یادآور":"یادآور جدید"}</h3><button onClick={()=>setEdit(null)}>×</button></div><label>عنوان<input autoFocus value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})} placeholder="مثلاً پرداخت قسط"/></label><label>توضیحات<input value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})} placeholder="اختیاری"/></label><div className="anp-reminder-grid"><label>تاریخ<input type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><label>ساعت<input type="time" value={edit.time} onChange={e=>setEdit({...edit,time:e.target.value})}/></label></div><label>تکرار<select value={edit.repeat} onChange={e=>setEdit({...edit,repeat:e.target.value as ReminderRepeat})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{edit.repeat==="custom"&&<div className="anp-reminder-days">{days.map((d,i)=><button key={d} className={edit.customDays?.includes(i)?"selected":""} onClick={()=>{const s=new Set(edit.customDays??[]);s.has(i)?s.delete(i):s.add(i);setEdit({...edit,customDays:[...s].sort()})}}>{d}</button>)}</div>}{error&&<p className="field-err">{error}</p>}<button className="primary-button" onClick={()=>void save()}>ذخیره یادآور</button></div></div>}
 </div>;
}
