const KEY="anp_services_personalization_v1";
const NAMES=["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
const text=(e:Element)=>((e as HTMLElement).innerText||e.getAttribute("aria-label")||"").replace(/\s+/g," ").trim();
const nameOf=(e:HTMLElement)=>NAMES.find(n=>text(e)===n||text(e).startsWith(n+" "))||"";
const buttons=()=>Array.from(document.querySelectorAll("button,[role='button']")) as HTMLElement[];
const get=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return x&&typeof x==="object"?x:{} }catch{return{}}};
const save=(x:Record<string,string[]>)=>localStorage.setItem(KEY,JSON.stringify(x));
function toast(message:string){document.getElementById("anp-service-toast")?.remove();const e=document.createElement("div");e.id="anp-service-toast";e.textContent=message;e.dir="rtl";e.style.cssText="position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:100010;background:rgba(2,20,29,.96);color:#fff;border:1px solid rgba(0,214,176,.35);border-radius:14px;padding:10px 16px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.25);pointer-events:none";document.body.appendChild(e);setTimeout(()=>e.remove(),1700)}
function installLongPress(el:HTMLElement,group:HTMLElement[]){if(el.dataset.anpDragInstalled)return;el.dataset.anpDragInstalled="1";el.style.touchAction="pan-y";let timer=0;let dragging=false;let startX=0,startY=0;let moved=false;const end=()=>{clearTimeout(timer);if(dragging){el.classList.remove("anp-dragging");dragging=false} };el.addEventListener("pointerdown",e=>{startX=e.clientX;startY=e.clientY;moved=false;timer=window.setTimeout(()=>{dragging=true;el.classList.add("anp-dragging");navigator.vibrate?.(18)},620)});el.addEventListener("pointermove",e=>{const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.hypot(dx,dy)>10)moved=true;if(!dragging||!moved)return;const target=group.find(x=>x!==el&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(target){target.parentElement?.insertBefore(el,target);persistGroup(group)}});el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end)}
function persistGroup(group:HTMLElement[]){const ids=group.map(nameOf).filter(Boolean);if(!ids.length)return;const all=get();all["home"]=[...new Set(ids)];save(all)}
function isHome(){const visible=buttons().filter(b=>NAMES.includes(nameOf(b))&&b.offsetParent!==null);return visible.length>=4 && !!visible[0]?.closest("main,section,div")}
function applyHome(){const all=get();const saved=all.home;if(!Array.isArray(saved)||!saved.length)return;const list=buttons().filter(b=>NAMES.includes(nameOf(b))&&b.offsetParent!==null);const parent=list[0]?.parentElement;if(!parent)return;const map=new Map(list.map(b=>[nameOf(b),b]));saved.forEach(n=>{const b=map.get(n);if(b)parent.appendChild(b)});list.forEach(b=>installLongPress(b,list))}
function openServices(){document.getElementById("anp-all-services-button")?.click()}
function AllServices({onClose}:{onClose:()=>void}){const saved=get().home||[];const order=[...new Set([...saved,...NAMES])];let down=0,dragging="";const move=(name:string,target:string)=>{if(name===target)return;const a=order.indexOf(name),b=order.indexOf(target);if(a<0||b<0)return;order.splice(a,1);order.splice(order.indexOf(target),0,name);const x=get();x.all=order;save(x)};return <div className="anp-personal-services" dir="rtl"><header><button onClick={onClose}>‹</button><div><b>همه خدمات</b><span>خدمات همیشه در دسترس هستند</span></div></header><main>{order.map(n=><button key={n} data-service={n} onPointerDown={()=>{down=window.setTimeout(()=>{dragging=n;navigator.vibrate?.(18)},620)}} onPointerMove={e=>{if(!dragging)return;const el=e.currentTarget;const target=(document.elementFromPoint(e.clientX,e.clientY) as HTMLElement|null)?.closest("[data-service]") as HTMLElement|null;if(target&&target.dataset.service){move(dragging,target.dataset.service)}}} onPointerUp={()=>{clearTimeout(down);if(dragging){dragging="";renderServices()}}} onPointerCancel={()=>{clearTimeout(down);dragging=""}} onClick={()=>{if(!dragging){const b=buttons().find(x=>nameOf(x)===n);onClose();setTimeout(()=>b?.click(),0)}}}><i>◉</i><span>{n}</span><em>›</em></button>)}</main><style>{`.anp-personal-services{min-height:100%;box-sizing:border-box;background:#020e18;color:#f4fafc;padding:calc(env(safe-area-inset-top) + 14px) 14px 24px;font-family:Vazirmatn,sans-serif}.anp-personal-services header{display:flex;gap:12px;align-items:center;padding:6px 0 18px}.anp-personal-services header>button{width:42px;height:42px;border:0;border-radius:13px;background:#0b2230;color:#fff;font-size:29px}.anp-personal-services header div{display:flex;flex-direction:column}.anp-personal-services header b{font-size:20px}.anp-personal-services header span{font-size:10px;color:#8ca0aa;margin-top:3px}.anp-personal-services main{display:grid;grid-template-columns:1fr 1fr;gap:10px}.anp-personal-services main button{min-height:78px;border:1px solid rgba(255,255,255,.07);border-radius:17px;background:#071a24;color:#fff;padding:11px;display:flex;align-items:center;gap:8px;font:700 12px Vazirmatn}.anp-personal-services i{width:34px;height:34px;border-radius:11px;background:rgba(0,214,176,.1);color:#00d6b0;display:grid;place-items:center;font-style:normal}.anp-personal-services main span{flex:1;text-align:right}.anp-personal-services em{color:#718892;font-style:normal;font-size:18px}.anp-dragging{opacity:.75;transform:scale(1.025);box-shadow:0 8px 24px rgba(0,214,176,.18)}`}</style></div>}
let renderServices=()=>{};
export function installServicePersonalization(){if(document.body.dataset.anpPersonalization)return;document.body.dataset.anpPersonalization="1";const observer=new MutationObserver(()=>applyHome());observer.observe(document.body,{childList:true,subtree:true});setTimeout(applyHome,500);}
export function mountPersonalizedServices(openAll:(cb:()=>void)=>void){openServices();renderServices=()=>undefined;}
export {AllServices};
