import { createRoot } from "react-dom/client";

const NAMES=["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
const HOME_KEY="anp_home_services_v3"; const ALL_KEY="anp_all_services_v3"; const CAPACITY=16;
const text=(e:Element)=>((e as HTMLElement).innerText||e.getAttribute("aria-label")||"").replace(/\s+/g," ").trim();
const serviceId=(e:Element)=>NAMES.find(n=>text(e)===n||text(e).startsWith(n+" "))||"";
const allButtons=()=>Array.from(document.querySelectorAll("button,[role=button]")) as HTMLElement[];
const findButton=(name:string)=>allButtons().find(b=>serviceId(b)===name)||null;
const read=(key:string, fallback:string[])=>{try{const x=JSON.parse(localStorage.getItem(key)||"null");return Array.isArray(x)?x.filter((n:string)=>NAMES.includes(n)):fallback}catch{return fallback}};
const write=(key:string,v:string[])=>localStorage.setItem(key,JSON.stringify([...new Set(v)]));
function toast(message:string){const old=document.getElementById("anp-service-toast");old?.remove();const el=document.createElement("div");el.id="anp-service-toast";el.textContent=message;el.dir="rtl";el.style.cssText="position:fixed;left:50%;bottom:105px;transform:translateX(-50%);z-index:100006;background:rgba(3,19,28,.96);color:#fff;border:1px solid rgba(0,214,176,.42);border-radius:14px;padding:11px 17px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.35);pointer-events:none;text-align:center";document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function saveDomOrder(){const visible=allButtons().map(serviceId).filter(Boolean);const home=read(HOME_KEY,visible.slice(0,CAPACITY));write(HOME_KEY,visible.filter(n=>home.includes(n)));}
function longPress(el:HTMLElement,handlers:{move?:(e:PointerEvent)=>void;drop?:(e:PointerEvent)=>void}){let timer=0,drag=false,down=false;const start=(e:PointerEvent)=>{if(e.pointerType==="mouse"&&e.button!==0)return;down=true;drag=false;timer=window.setTimeout(()=>{if(!down)return;drag=true;el.classList.add("anp-dragging");el.style.touchAction="none";navigator.vibrate?.(15)},600)};el.addEventListener("pointerdown",start);el.addEventListener("pointermove",e=>{if(drag){e.preventDefault();handlers.move?.(e)}});el.addEventListener("pointerup",e=>{down=false;clearTimeout(timer);if(drag){handlers.drop?.(e);e.preventDefault()}el.classList.remove("anp-dragging");el.style.touchAction="manipulation";drag=false});el.addEventListener("pointercancel",()=>{down=false;clearTimeout(timer);el.classList.remove("anp-dragging");el.style.touchAction="manipulation"})}
function installHome(){const buttons=allButtons().filter(b=>NAMES.includes(serviceId(b))&&b.offsetParent!==null&&!b.dataset.anpCustomDrag);if(!buttons.length)return;const parent=buttons[0].parentElement;if(!parent)return;let home=read(HOME_KEY,buttons.map(serviceId).slice(0,CAPACITY));home=home.filter(n=>buttons.some(b=>serviceId(b)===n));if(!home.length)home=buttons.map(serviceId).slice(0,CAPACITY);const allOrder=read(ALL_KEY,NAMES);const hidden=NAMES.filter(n=>!home.includes(n));write(HOME_KEY,home);write(ALL_KEY,[...allOrder.filter(n=>hidden.includes(n)),...hidden.filter(n=>!allOrder.includes(n))]);const map=new Map(buttons.map(b=>[serviceId(b),b]));NAMES.forEach(n=>{const b=map.get(n);if(b)b.style.display=home.includes(n)?"":"none"});home.forEach(n=>{const b=map.get(n);if(b)parent.appendChild(b)});
 let dropZone=document.getElementById("anp-home-all-drop");if(!dropZone){dropZone=document.createElement("div");dropZone.id="anp-home-all-drop";dropZone.textContent="برای انتقال خدمت، لمس طولانی کنید و به «همه خدمات» بکشید";dropZone.style.cssText="display:none;margin:6px 0;padding:8px 10px;border:1px dashed rgba(0,214,176,.35);border-radius:12px;color:#8ca0aa;text-align:center;font:600 10px Vazirmatn";parent.appendChild(dropZone)}
 const allBtn=document.getElementById("anp-all-services-button");buttons.forEach(el=>{el.dataset.anpCustomDrag="1";longPress(el,{move:e=>{if(dropZone)dropZone.style.display="block";const over=allBtn?.getBoundingClientRect();if(over&&e.clientX>=over.left&&e.clientX<=over.right&&e.clientY>=over.top&&e.clientY<=over.bottom)allBtn.classList.add("anp-drop-target");else allBtn?.classList.remove("anp-drop-target");const target=buttons.find(x=>x!==el&&x.style.display!=="none"&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(target)target.parentElement?.insertBefore(el,target)},drop:e=>{dropZone!.style.display="none";allBtn?.classList.remove("anp-drop-target");const name=serviceId(el);const r=allBtn?.getBoundingClientRect();if(r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){home=home.filter(n=>n!==name);el.style.display="none";write(HOME_KEY,home);const ao=read(ALL_KEY,NAMES).filter(n=>n!==name);write(ALL_KEY,[...ao,name]);toast(`${name} به همه خدمات منتقل شد.`);return}home=Array.from(parent.querySelectorAll("button,[role=button]")).map(serviceId).filter(n=>home.includes(n));write(HOME_KEY,home);write(ALL_KEY,read(ALL_KEY,NAMES).filter(n=>!home.includes(n)))}})});
}
function openServices(){const host=document.createElement("div");host.id="anp-custom-services-root";Object.assign(host.style,{position:"fixed",inset:"0",zIndex:"100000"});document.body.appendChild(host);const close=()=>{root.unmount();host.remove()};const root=createRoot(host);root.render(<AllServices onClose={close}/>)}
function AllServices({onClose}:{onClose:()=>void}){const [order,setOrder]=React.useState(()=>{const home=read(HOME_KEY,NAMES.slice(0,CAPACITY));const stored=read(ALL_KEY,NAMES);return [...stored.filter(n=>!home.includes(n)),...NAMES.filter(n=>!home.includes(n)&&!stored.includes(n))]});const [home,setHome]=React.useState(()=>read(HOME_KEY,NAMES.slice(0,CAPACITY)));const add=(name:string)=>{if(home.includes(name))return;if(home.length>=CAPACITY){toast("فضای صفحه اصلی پر است. یک خدمت را به همه خدمات منتقل کنید.");return}const next=[...home,name];setHome(next);write(HOME_KEY,next);setOrder(o=>o.filter(n=>n!==name));const b=findButton(name);if(b){b.style.display="";const ref=findButton(next[next.length-2]);ref?.parentElement?.appendChild(b)}toast(`${name} به صفحه اصلی اضافه شد.`)};const reorder=(from:number,to:number)=>{if(from===to)return;setOrder(o=>{const a=[...o],x=a.splice(from,1)[0];a.splice(to,0,x);write(ALL_KEY,a);return a})};return <div className="anp-all-services" dir="rtl"><header><button onClick={onClose}>‹</button><div><b>همه خدمات</b><span>خدمت‌ها حذف نمی‌شوند؛ فقط از صفحه اصلی خارج می‌شوند.</span></div></header><div className="anp-home-drop">↥ لمس طولانی و کشیدن خدمت به این قسمت = افزودن به صفحه اصلی</div><main>{order.map((n,i)=><ServiceRow key={n} name={n} index={i} onReorder={reorder} onAdd={()=>add(n)}/>)}</main><style>{`.anp-all-services{min-height:100%;box-sizing:border-box;background:#020e18;color:#f4fafc;padding:calc(env(safe-area-inset-top) + 14px) 14px 24px;font-family:Vazirmatn,sans-serif}.anp-all-services header{display:flex;gap:12px;align-items:center;padding:6px 0 18px}.anp-all-services header>button{width:42px;height:42px;border:1px solid rgba(255,255,255,.08);border-radius:13px;background:#0b2230;color:#fff;font-size:29px}.anp-all-services header div{display:flex;flex-direction:column}.anp-all-services header b{font-size:20px}.anp-all-services header span{font-size:10px;color:#8ca0aa;margin-top:3px}.anp-home-drop{padding:11px;border:1px dashed rgba(0,214,176,.35);border-radius:14px;color:#8ca0aa;text-align:center;font:600 10px Vazirmatn;margin-bottom:11px}.anp-all-services main{display:grid;grid-template-columns:1fr 1fr;gap:10px}.anp-all-services main button{min-height:78px;border:1px solid rgba(255,255,255,.07);border-radius:17px;background:#071a24;color:#fff;padding:11px;display:flex;align-items:center;gap:8px;font:700 12px Vazirmatn}.anp-all-services main button.anp-dragging{transform:scale(.98);box-shadow:0 0 0 2px rgba(0,214,176,.32)}.anp-all-services i{width:34px;height:34px;border-radius:11px;background:rgba(0,214,176,.1);color:#00d6b0;display:grid;place-items:center;font-style:normal}.anp-all-services main span{flex:1;text-align:right}.anp-all-services em{color:#718892;font-style:normal;font-size:18px}`}</style></div>}
function ServiceRow({name,index,onReorder,onAdd}:{name:string;index:number;onReorder:(a:number,b:number)=>void;onAdd:()=>void}){const ref=React.useRef<HTMLButtonElement>(null);longPress(ref.current!,{move:e=>{const buttons=Array.from(document.querySelectorAll(".anp-all-services main button")) as HTMLElement[];const t=buttons.find(x=>x!==ref.current&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(t){const to=buttons.indexOf(t);if(to>=0)onReorder(index,to)}},drop:e=>{const r=document.querySelector(".anp-home-drop")?.getBoundingClientRect();if(r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)onAdd()}});return <button ref={ref}><i>◉</i><span>{name}{name==="چک صیادی"&&<small>ثبت چک · استعلام چک‌های من</small>}</span><em>›</em></button>}
export function installServiceCustomization(){const style=document.createElement("style");style.id="anp-service-customization-style";style.textContent=".anp-drop-target{outline:2px solid #00d6b0!important;transform:scale(1.02)}.anp-dragging{box-shadow:0 0 0 2px rgba(0,214,176,.35)!important;opacity:.92}";document.head.appendChild(style);document.addEventListener("click",e=>{const b=(e.target as HTMLElement)?.closest("#anp-all-services-button") as HTMLElement|null;if(b){e.preventDefault();e.stopImmediatePropagation();openServices()}},true);const obs=new MutationObserver(()=>installHome());obs.observe(document.body,{childList:true,subtree:true});setTimeout(installHome,400);setTimeout(installHome,1200)}
