const KEY = "anp_service_personalization_v2";
const CAPACITY = 16;
const NAMES = ["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
type State={home:string[];all:string[]};
const clean=(s:string)=>s.replace(/\s+/g," ").trim();
const textOf=(e:Element)=>clean((e as HTMLElement).innerText||e.getAttribute("aria-label")||e.getAttribute("title")||"");
const service=(e:Element)=>{const t=textOf(e);return NAMES.find(n=>t===n||t.startsWith(n+" "))||""};
const read=():State=>{try{const s=JSON.parse(localStorage.getItem(KEY)||"{}");return{home:Array.isArray(s.home)?s.home:[],all:Array.isArray(s.all)?s.all:[]}}catch{return{home:[],all:[]}}};
const write=(s:State)=>localStorage.setItem(KEY,JSON.stringify({home:[...new Set(s.home)].filter(Boolean).slice(0,CAPACITY),all:[...new Set(s.all)].filter(Boolean)}));
const visible=(e:Element)=>{const h=e as HTMLElement,r=h.getBoundingClientRect();return h.offsetParent!==null&&r.width>0&&r.height>0};
const feedback=()=>{try{navigator.vibrate?.(18)}catch{}};
function sound(kind:"remove"|"add"){try{const Ctx=window.AudioContext||(window as any).webkitAudioContext;if(!Ctx)return;const c=new Ctx(),o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.value=kind==="remove"?420:680;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.035,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.11);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch{}}
function toast(msg:string){document.getElementById("anp-service-toast")?.remove();const e=document.createElement("div");e.id="anp-service-toast";e.dir="rtl";e.textContent=msg;e.style.cssText="position:fixed;left:50%;bottom:86px;transform:translateX(-50%);z-index:100600;background:rgba(5,20,27,.97);color:#fff;border:1px solid rgba(0,214,176,.35);border-radius:13px;padding:9px 14px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 10px 30px rgba(0,0,0,.32);pointer-events:none;white-space:nowrap";document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}
function confetti(){const l=document.createElement("div");l.id="anp-service-confetti";l.dir="ltr";for(let i=0;i<16;i++){const p=document.createElement("i");p.style.setProperty("--x",`${(Math.random()-.5)*220}px`);p.style.setProperty("--r",`${Math.random()*360}deg`);p.style.setProperty("--d",`${Math.random()*70}ms`);l.appendChild(p)}document.body.appendChild(l);setTimeout(()=>l.remove(),650)}
function serviceItems():HTMLElement[]{return Array.from(document.querySelectorAll("button,[role=button]")).filter(e=>visible(e)&&!!service(e)) as HTMLElement[]}
function homeItems():HTMLElement[]{const items=serviceItems();const groups=new Map<HTMLElement,HTMLElement[]>();for(const b of items){const p=b.parentElement;if(p)groups.set(p,[...(groups.get(p)||[]),b])}let best:HTMLElement[]=[];for(const v of groups.values())if(v.length>best.length)best=v;return best.length>=2?best:[]}
function allRoot():HTMLElement|null{const marked=document.querySelector("[data-anp-all-services],.anp-all-services,#anp-all-services") as HTMLElement|null;if(marked)return marked;const h=Array.from(document.querySelectorAll("h1,h2,h3,[role=heading]")).find(e=>/همه\s*خدمات/.test(textOf(e)));if(!h)return null;let p=h.parentElement;for(let i=0;i<7&&p;i++,p=p.parentElement){if(Array.from(p.querySelectorAll("button,[role=button]")).filter(e=>!!service(e)).length>=3)return p}return null}
function allItems():HTMLElement[]{const r=allRoot();return r?Array.from(r.querySelectorAll("button,[role=button]")).filter(e=>visible(e)&&!!service(e)) as HTMLElement[]:[]}
function allServicesButton(){return Array.from(document.querySelectorAll("button,[role=button]")).find(e=>/همه\s*خدمات/.test(textOf(e))) as HTMLElement|null}
function homeButton(){return Array.from(document.querySelectorAll("button,[role=button]")).find(e=>/صفحه\s*اصلی|بازگشت\s*به\s*خانه/.test(textOf(e))) as HTMLElement|null}
function ensure(names:string[]){const s=read();const all=[...s.all];for(const n of names)if(!all.includes(n))all.push(n);let home=s.home.filter(n=>names.includes(n));if(!s.home.length)home=names.slice(0,CAPACITY);write({home,all});return read()}
function applyOrder(items:HTMLElement[],order:string[]){const rank=new Map(order.map((n,i)=>[n,i]));for(const e of items){const n=service(e);if(!n)continue;e.style.setProperty("order",String(rank.has(n)?rank.get(n):9999));e.classList.toggle("anp-service-hidden",!order.includes(n))}}
function installDrag(el:HTMLElement,fromHome:boolean,getItems:()=>HTMLElement[]){if(el.dataset.anpSafeDrag==="1")return;el.dataset.anpSafeDrag="1";el.style.touchAction="manipulation";let timer=0,active=false,down=false,sx=0,sy=0,target:HTMLElement|null=null;const cleanUp=()=>{clearTimeout(timer);down=false;active=false;el.classList.remove("anp-service-dragging");for(const x of getItems())x.classList.remove("anp-service-drop-hover");document.getElementById("anp-service-drop-target")?.remove();target=null;el.style.touchAction="manipulation"};el.addEventListener("pointerdown",e=>{if(e.button!==0)return;down=true;sx=e.clientX;sy=e.clientY;timer=window.setTimeout(()=>{if(!down)return;active=true;try{el.setPointerCapture(e.pointerId)}catch{}el.classList.add("anp-service-dragging");if(fromHome){const z=document.createElement("div");z.id="anp-service-drop-target";z.dir="rtl";z.textContent="همه خدمات";document.body.appendChild(z)}feedback()},520),{passive:true});el.addEventListener("pointermove",e=>{if(!active){if(Math.hypot(e.clientX-sx,e.clientY-sy)>10)clearTimeout(timer);return}e.preventDefault();if(fromHome){const z=document.getElementById("anp-service-drop-target");if(z){const r=z.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){z.classList.add("active");target=z}else{z.classList.remove("active");if(target===z)target=null}}}const items=getItems().filter(x=>x!==el&&!x.classList.contains("anp-service-hidden"));const t=items.find(x=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})||null;if(t){target=t;for(const x of items)x.classList.toggle("anp-service-drop-hover",x===t)}},{passive:false});el.addEventListener("pointerup",e=>{if(!active){cleanUp();return}e.preventDefault();const n=service(el),st=read(),z=document.getElementById("anp-service-drop-target");const zr=z?.getBoundingClientRect();const toAll=!!(fromHome&&zr&&e.clientX>=zr.left&&e.clientX<=zr.right&&e.clientY>=zr.top&&e.clientY<=zr.bottom);if(toAll&&n){write({home:st.home.filter(v=>v!==n),all:st.all.includes(n)?st.all:[...st.all,n]});toast(`${n} به همه خدمات منتقل شد.`);sound("remove");feedback();confetti();setTimeout(()=>allServicesButton()?.click(),90)}else if(target&&target!==z&&n){const names=getItems().map(service).filter(Boolean).filter(v=>v!==n);const ti=names.indexOf(service(target));names.splice(Math.max(0,ti),0,n);if(fromHome)write({home:names.slice(0,CAPACITY),all:st.all});else write({home:st.home,all:names});const order=fromHome?names.slice(0,CAPACITY):names;applyOrder(getItems(),order);feedback()}cleanUp()},{passive:false});el.addEventListener("pointercancel",cleanUp);el.addEventListener("contextmenu",e=>{if(active)e.preventDefault()})}
function homeApply(){const items=homeItems();if(items.length<2)return;const names=items.map(service).filter(Boolean);const s=ensure(names);const order=[...s.home.filter(n=>names.includes(n)),...names.filter(n=>!s.home.includes(n))].slice(0,CAPACITY);write({home:order,all:[...s.all,...names.filter(n=>!s.all.includes(n))]});applyOrder(items,order);items.forEach(e=>installDrag(e,true,homeItems))}
function allApply(){const items=allItems();if(items.length<2)return;const names=items.map(service).filter(Boolean);const s=ensure(names);const order=[...s.all.filter(n=>names.includes(n)),...names.filter(n=>!s.all.includes(n))];write({home:s.home,all:order});applyOrder(items,order);items.forEach(e=>installDrag(e,false,allItems))}
function financeGlow(){const e=Array.from(document.querySelectorAll("button,[role=button]")).find(x=>/مرکز\s*مالی\s*دخل\s*و\s*خرج|دخل\s*و\s*خرج/.test(textOf(x))) as HTMLElement|null;if(e)e.classList.add("anp-finance-glow")}
export function installServiceCustomizationV3(){if((document.body as any).dataset.anpSafePersonalization)return;(document.body as any).dataset.anpSafePersonalization="1";const style=document.createElement("style");style.textContent=`
.anp-service-hidden{display:none!important}
.anp-service-dragging{transform:scale(1.025)!important;opacity:.9!important;z-index:1000!important;box-shadow:0 8px 24px rgba(0,0,0,.18)!important;outline:1.5px solid rgba(0,214,176,.55)!important;transition:none!important}.anp-service-dragging *{pointer-events:none!important}
.anp-service-drop-hover{outline:2px solid rgba(0,214,176,.65)!important;transform:translateY(-2px)!important}
#anp-service-drop-target{position:fixed;left:50%;bottom:82px;transform:translateX(-50%);z-index:100700;min-width:90px;text-align:center;padding:10px 18px;border-radius:15px;border:1px dashed rgba(0,214,176,.6);background:rgba(5,22,29,.95);color:#fff;font:800 12px Vazirmatn,sans-serif;pointer-events:none;box-shadow:0 8px 28px rgba(0,0,0,.3);transition:.16s}#anp-service-drop-target.active{transform:translateX(-50%) scale(1.06);border-style:solid;box-shadow:0 0 0 5px rgba(0,214,176,.08),0 10px 30px rgba(0,0,0,.3)}
.anp-finance-glow{position:relative!important;overflow:visible!important}.anp-finance-glow::after{content:"";position:absolute;inset:-1px;border-radius:inherit;padding:1.5px;background:conic-gradient(from 0deg,transparent 0deg,transparent 292deg,rgba(0,214,176,.04) 318deg,rgba(0,214,176,.72) 342deg,rgba(255,214,96,.45) 352deg,transparent 360deg);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;pointer-events:none;animation:anpFinanceSweep 4.2s linear infinite}@keyframes anpFinanceSweep{to{transform:rotate(360deg)}}
#anp-service-confetti{position:fixed;left:50%;top:45%;width:1px;height:1px;z-index:100800;pointer-events:none}#anp-service-confetti i{position:absolute;width:6px;height:10px;border-radius:2px;background:rgba(0,214,176,.9);animation:anpConfetti .62s cubic-bezier(.2,.7,.2,1) var(--d) both}#anp-service-confetti i:nth-child(3n){background:rgba(255,210,80,.9)}#anp-service-confetti i:nth-child(4n){background:rgba(150,110,255,.9)}@keyframes anpConfetti{to{transform:translate(var(--x),120px) rotate(var(--r));opacity:0}}
`;document.head.appendChild(style);let scheduled=false;const run=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;try{homeApply();allApply();financeGlow()}catch{}})};run();setTimeout(run,500);setTimeout(run,1200);setTimeout(run,2200)}
