const KEY="anp_home_services_v3";
const NAMES=["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
const text=(e:Element)=>((e as HTMLElement).innerText||e.getAttribute("aria-label")||"").replace(/\s+/g," ").trim();
const nameOf=(e:HTMLElement)=>NAMES.find(n=>text(e)===n||text(e).startsWith(n+" "))||"";
const allButtons=()=>Array.from(document.querySelectorAll("button,[role='button']")) as HTMLElement[];
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return x&&typeof x==="object"?x as {home?:string[]}:{} }catch{return{}}}
function write(home:string[]){localStorage.setItem(KEY,JSON.stringify({home:[...new Set(home.filter(Boolean))]}))}
function toast(message:string){document.getElementById("anp-service-toast")?.remove();const e=document.createElement("div");e.id="anp-service-toast";e.textContent=message;e.dir="rtl";e.style.cssText="position:fixed;left:50%;bottom:94px;transform:translateX(-50%);z-index:100020;background:rgba(2,19,28,.97);color:#fff;border:1px solid rgba(0,214,176,.45);border-radius:14px;padding:10px 16px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.3);pointer-events:none;white-space:nowrap";document.body.appendChild(e);setTimeout(()=>e.remove(),1700)}
function findHomeGroup(){const list=allButtons().filter(b=>NAMES.includes(nameOf(b))&&b.offsetParent!==null);if(list.length<3)return null;const parent=list[0].parentElement;if(!parent)return null;const siblings=list.filter(b=>b.parentElement===parent);return siblings.length>=3?{parent,list:siblings}:null}
function saveCurrent(list:HTMLElement[]){const r=read();write(list.map(nameOf).concat(r.home||[]))}
function installLongPress(el:HTMLElement,getGroup:()=>HTMLElement[]){if(el.dataset.anpServiceDrag)return;el.dataset.anpServiceDrag="1";el.style.touchAction="pan-y";let timer=0;let dragging=false;let moved=false;let sx=0,sy=0;const cancel=()=>{clearTimeout(timer);el.classList.remove("anp-service-dragging");dragging=false};el.addEventListener("pointerdown",e=>{sx=e.clientX;sy=e.clientY;moved=false;timer=window.setTimeout(()=>{dragging=true;el.classList.add("anp-service-dragging");navigator.vibrate?.(18)},650)});el.addEventListener("pointermove",e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>10)moved=true;if(!dragging||!moved)return;e.preventDefault();const allTarget=document.getElementById("anp-all-services-button");if(allTarget){const r=allTarget.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){const n=nameOf(el);el.style.display="none";const group=getGroup().filter(x=>x!==el);saveCurrent(group);toast(`${n} به همه خدمات منتقل شد.`);cancel();return}}const group=getGroup();const target=group.find(x=>x!==el&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(target){target.parentElement?.insertBefore(el,target);saveCurrent(getGroup())}});el.addEventListener("pointerup",()=>{if(dragging)saveCurrent(getGroup());cancel()});el.addEventListener("pointercancel",cancel)}
function apply(){const g=findHomeGroup();if(!g)return;let r=read();let home=Array.isArray(r.home)&&r.home.length?r.home:g.list.map(nameOf);const available=new Map(g.list.map(b=>[nameOf(b),b]));home=home.filter(n=>available.has(n));g.list.forEach(b=>{const n=nameOf(b);if(!home.includes(n)&&home.length<NAMES.length)home.push(n)});home.forEach(n=>{const b=available.get(n);if(b)g.parent.appendChild(b)});write(home);g.list.forEach(b=>installLongPress(b,()=>findHomeGroup()?.list||[]))}
export function installServiceCustomization(){if(document.body.dataset.anpServiceCustomization)return;document.body.dataset.anpServiceCustomization="1";const style=document.createElement("style");style.textContent=".anp-service-dragging{outline:2px solid rgba(0,214,176,.72)!important;transform:scale(1.025);opacity:.82!important;z-index:20!important;box-shadow:0 8px 28px rgba(0,214,176,.18)!important}.anp-service-dragging *{pointer-events:none}";document.head.appendChild(style);const run=()=>apply();new MutationObserver(run).observe(document.body,{childList:true,subtree:true});setTimeout(run,450);setTimeout(run,1200)}
