const KEY="anp_service_personalization_v1";
const CAPACITY=16;
const NAMES=["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
type State={home:string[];all:string[]};
const clean=(s:string)=>s.replace(/\s+/g," ").trim();
const label=(e:Element)=>clean((e as HTMLElement).innerText||e.getAttribute("aria-label")||e.getAttribute("title")||"");
const service=(e:Element)=>NAMES.find(n=>label(e)===n||label(e).startsWith(n+" "))||"";
const read=():State=>{try{const s=JSON.parse(localStorage.getItem(KEY)||"{}");return {home:Array.isArray(s.home)?s.home:[],all:Array.isArray(s.all)?s.all:[]}}catch{return {home:[],all:[]}}};
const write=(s:State)=>localStorage.setItem(KEY,JSON.stringify({home:[...new Set(s.home)].filter(Boolean).slice(0,CAPACITY),all:[...new Set(s.all)].filter(Boolean)}));
function toast(msg:string){document.getElementById("anp-personal-toast")?.remove();const e=document.createElement("div");e.id="anp-personal-toast";e.dir="rtl";e.textContent=msg;e.style.cssText="position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:100200;background:rgba(4,22,30,.97);color:#fff;border:1px solid rgba(0,214,176,.42);border-radius:13px;padding:10px 15px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 8px 28px rgba(0,0,0,.3);pointer-events:none;white-space:nowrap";document.body.appendChild(e);setTimeout(()=>e.remove(),1700)}
function isHomePage(){return Array.from(document.querySelectorAll("h1,h2,h3,[role=heading]")).some(e=>/صفحه اصلی|خانه/.test(label(e)));}
function homeGroup(){const buttons=Array.from(document.querySelectorAll("button,[role=button]")).filter(e=>{const h=e as HTMLElement;return h.offsetParent!==null&&!!service(h)}) as HTMLElement[];const groups=new Map<HTMLElement,HTMLElement[]>();for(const b of buttons){const p=b.parentElement;if(!p)continue;groups.set(p,[...(groups.get(p)||[]),b])}let best:{parent:HTMLElement;items:HTMLElement[]}|null=null;for(const [parent,items] of groups)if(!best||items.length>best.items.length)best={parent,items};return best&&best.items.length>=2?best:null;}
function allServicesRoot(){const marked=document.querySelector("[data-anp-all-services],.anp-all-services,#anp-all-services");if(marked)return marked as HTMLElement;const heading=Array.from(document.querySelectorAll("h1,h2,h3,[role=heading]")).find(e=>/همه\s*خدمات/.test(label(e)));if(!heading)return null;let p=heading.parentElement;for(let i=0;i<6&&p;i++,p=p.parentElement){const count=Array.from(p.querySelectorAll("button,[role=button]")).filter(e=>!!service(e)).length;if(count>=3)return p}return null;}
function allButton(){return Array.from(document.querySelectorAll("button,[role=button]")).find(e=>/همه\s*خدمات/.test(label(e))) as HTMLElement|null;}
function homeButton(){return Array.from(document.querySelectorAll("button,[role=button]")).find(e=>/صفحه\s*اصلی|بازگشت\s*به\s*خانه/.test(label(e))) as HTMLElement|null;}
function feedback(){try{navigator.vibrate?.(18)}catch{}}
function ensureState(names:string[]){const s=read();const all=[...s.all];for(const n of names)if(!all.includes(n))all.push(n);let home=s.home.filter(n=>names.includes(n));if(!s.home.length)home=all.slice(0,CAPACITY).filter(n=>names.includes(n));write({home,all});return read();}
function reorder(parent:HTMLElement,items:HTMLElement[],order:string[]){const map=new Map(items.map(x=>[service(x),x]));const desired=order.map(n=>map.get(n)).filter(Boolean) as HTMLElement[];const current=items.filter(x=>desired.includes(x));if(current.length!==desired.length||current.some((x,i)=>x!==desired[i])){for(const el of desired)parent.appendChild(el)}}
function installDrag(el:HTMLElement,getItems:()=>{parent:HTMLElement;items:HTMLElement[]}|null,getOrder:()=>string[],setOrder:(o:string[])=>void,onDrop:(el:HTMLElement,x:number,y:number)=>boolean){if(el.dataset.anpPersonalDrag)return;el.dataset.anpPersonalDrag="1";el.style.touchAction="manipulation";let timer=0,drag=false,down=false,moved=false,sx=0,sy=0;const reset=()=>{clearTimeout(timer);down=false;drag=false;moved=false;el.classList.remove("anp-personal-dragging");el.style.touchAction="manipulation"};el.addEventListener("pointerdown",e=>{down=true;moved=false;sx=e.clientX;sy=e.clientY;timer=window.setTimeout(()=>{if(!down)return;drag=true;el.classList.add("anp-personal-dragging");el.style.touchAction="none";feedback()},560)});el.addEventListener("pointermove",e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>14)moved=true;if(!drag||!moved)return;e.preventDefault();const g=getItems();if(!g)return;if(onDrop(el,e.clientX,e.clientY))return;const target=g.items.find(x=>x!==el&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(target){g.parent.insertBefore(el,target);setOrder(g.items.map(service).filter(Boolean))}});el.addEventListener("pointerup",e=>{if(drag){if(onDrop(el,e.clientX,e.clientY)){}else{const g=getItems();if(g)setOrder(g.items.map(service).filter(Boolean))}}reset()});el.addEventListener("pointercancel",reset);el.addEventListener("pointerleave",()=>{if(!drag)clearTimeout(timer)})}
function applyHome(){if(!isHomePage())return;const g=homeGroup();if(!g)return;const names=g.items.map(service).filter(Boolean);const s=ensureState(names);const order=s.home.filter(n=>names.includes(n));for(const n of names)if(!order.includes(n)&&order.length<CAPACITY)order.push(n);write({home:order,all:[...s.all,...names.filter(n=>!s.all.includes(n))]});reorder(g.parent,g.items,order);for(const b of g.items){const n=service(b);b.style.display=order.includes(n)?"":"none";installDrag(b,homeGroup,()=>read().home,o=>{const st=read();write({home:o,all:st.all})},(el,x,y)=>{const target=allButton();if(!target)return false;const r=target.getBoundingClientRect();if(x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom){const n=service(el);const st=read();write({home:st.home.filter(v=>v!==n),all:st.all.includes(n)?st.all:[...st.all,n]});toast(`${n} به همه خدمات منتقل شد.`);feedback();el.style.display="none";return true}return false})}}
function applyAll(){const root=allServicesRoot();if(!root)return;const items=Array.from(root.querySelectorAll("button,[role=button]")).filter(e=>!!service(e)) as HTMLElement[];if(items.length<2)return;const names=items.map(service).filter(Boolean);const s=ensureState(names);const order=s.all.filter(n=>names.includes(n));for(const n of names)if(!order.includes(n))order.push(n);write({home:s.home,all:[...order,...s.all.filter(n=>!order.includes(n))]});reorder(root,items,order);for(const el of items)installDrag(el,()=>({parent:root,items:Array.from(root.querySelectorAll("button,[role=button]")).filter(e=>!!service(e)) as HTMLElement[]}),()=>read().all,o=>{const st=read();write({home:st.home,all:o})},(item,x,y)=>{const hb=homeButton();if(!hb)return false;const r=hb.getBoundingClientRect();if(x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom){const n=service(item);const st=read();if(st.home.includes(n)){toast(`${n} از قبل در صفحه اصلی است.`);return true}if(st.home.length>=CAPACITY){toast("فضای صفحه اصلی پر است. یک خدمت را به همه خدمات منتقل کنید.");return true}write({home:[...st.home,n],all:st.all});toast(`${n} به صفحه اصلی اضافه شد.`);feedback();return true}return false})}
export function installServiceCustomizationV3(){if((document.body as any).dataset.anpPersonalV3)return;(document.body as any).dataset.anpPersonalV3="1";const style=document.createElement("style");style.textContent=".anp-personal-dragging{outline:2px solid rgba(0,214,176,.65)!important;transform:scale(1.025);opacity:.82!important;z-index:100!important;box-shadow:0 8px 28px rgba(0,214,176,.18)!important}.anp-personal-dragging *{pointer-events:none}";document.head.appendChild(style);let queued=false,suppressUntil=0;const run=()=>{if(performance.now()<suppressUntil)return;if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;applyHome();applyAll();suppressUntil=performance.now()+40})};new MutationObserver(run).observe(document.body,{childList:true,subtree:true});setTimeout(run,500);setTimeout(run,1200)}
