import React from "react";
import { createRoot } from "react-dom/client";

const NAMES=["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
const HOME_KEY="anp_home_services_v3",ALL_KEY="anp_all_services_v3",CAPACITY=16;
const text=(e:Element)=>((e as HTMLElement).innerText||e.getAttribute("aria-label")||"").replace(/\s+/g," ").trim();
const serviceId=(e:Element)=>NAMES.find(n=>text(e)===n||text(e).startsWith(n+" "))||"";
const allButtons=()=>Array.from(document.querySelectorAll("button,[role=button]")) as HTMLElement[];
const findButton=(name:string)=>allButtons().find(b=>serviceId(b)===name)||null;
const read=(key:string,fallback:string[])=>{try{const x=JSON.parse(localStorage.getItem(key)||"null");return Array.isArray(x)?x.filter((n:string)=>NAMES.includes(n)):fallback}catch{return fallback}};
const write=(key:string,v:string[])=>localStorage.setItem(key,JSON.stringify([...new Set(v)]));
function toast(message:string){const old=document.getElementById("anp-service-toast");old?.remove();const el=document.createElement("div");el.id="anp-service-toast";el.textContent=message;el.dir="rtl";el.style.cssText="position:fixed;left:50%;bottom:105px;transform:translateX(-50%);z-index:100006;background:rgba(3,19,28,.96);color:#fff;border:1px solid rgba(0,214,176,.42);border-radius:14px;padding:11px 17px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.35);pointer-events:none;text-align:center";document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function longPress(el:HTMLElement,handlers:{move?:(e:PointerEvent)=>void;drop?:(e:PointerEvent)=>void}){let timer=0,drag=false,down=false;el.style.touchAction="manipulation";el.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse"&&e.button!==0)return;down=true;timer=window.setTimeout(()=>{if(!down)return;drag=true;el.classList.add("anp-dragging");el.style.touchAction="none";navigator.vibrate?.(15)},600)});el.addEventListener("pointermove",e=>{if(drag){e.preventDefault();handlers.move?.(e)}});el.addEventListener("pointerup",e=>{down=false;clearTimeout(timer);if(drag){handlers.drop?.(e);e.preventDefault()}el.classList.remove("anp-dragging");el.style.touchAction="manipulation";drag=false});el.addEventListener("pointercancel",()=>{down=false;clearTimeout(timer);el.classList.remove("anp-dragging");el.style.touchAction="manipulation";drag=false})}
function installHome(){const buttons=allButtons().filter(b=>NAMES.includes(serviceId(b))&&b.offsetParent!==null&&!b.dataset.anpCustomDrag);if(!buttons.length)return;const parent=buttons[0].parentElement;if(!parent)return;let home=read(HOME_KEY,buttons.map(serviceId).slice(0,CAPACITY));if(!home.length)home=buttons.map(serviceId).slice(0,CAPACITY);home=home.filter(n=>buttons.some(b=>serviceId(b)===n));const map=new Map(buttons.map(b=>[serviceId(b),b]));buttons.forEach(b=>{b.style.display=home.includes(serviceId(b))?"":"none"});home.forEach(n=>map.get(n)&&parent.appendChild(map.get(n)!));write(HOME_KEY,home);
 let allBtn=document.getElementById("anp-all-services-button");if(!allBtn){allBtn=document.createElement("button");allBtn.id="anp-all-services-button";allBtn.innerHTML="<b>＋</b><span>همه خدمات</span>";allBtn.style.cssText="border:1px solid rgba(0,214,176,.25);background:rgba(0,214,176,.07);color:inherit;border-radius:16px;padding:12px;display:flex;align-items:center;justify-content:center;gap:7px;font:800 13px Vazirmatn";allBtn.onclick=()=>openServices();parent.appendChild(allBtn)}
 let drop=document.getElementById("anp-home-all-drop");if(!drop){drop=document.createElement("div");drop.id="anp-home-all-drop";drop.textContent="برای انتقال خدمت، لمس طولانی کنید و به «همه خدمات» بکشید";drop.style.cssText="display:none;margin:6px 0;padding:8px 10px;border:1px dashed rgba(0,214,176,.35);border-radius:12px;color:#8ca0aa;text-align:center;font:600 10px Vazirmatn";parent.appendChild(drop)}
 buttons.forEach(el=>{el.dataset.anpCustomDrag="1";longPress(el,{move:e=>{drop!.style.display="block";const ar=allBtn!.getBoundingClientRect();allBtn!.classList.toggle("anp-drop-target",e.clientX>=ar.left&&e.clientX<=ar.right&&e.clientY>=ar.top&&e.clientY<=ar.bottom);const t=buttons.find(x=>x!==el&&x.style.display!=="none"&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(t)t.parentElement?.insertBefore(el,t)},drop:e=>{drop!.style.display="none";allBtn!.classList.remove("anp-drop-target");const name=serviceId(el),r=allBtn!.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){el.style.display="none";home=home.filter(n=>n!==name);write(HOME_KEY,home);const ao=read(ALL_KEY,NAMES).filter(n=>n!==name);write(ALL_KEY,[...ao,name]);toast(`${name} به همه خدمات منتقل شد.`)}else{home=Array.from(parent.querySelectorAll("button,[role=button]")).map(serviceId).filter(n=>home.includes(n));write(HOME_KEY,home);write(ALL_KEY,read(ALL_KEY,NAMES).filter(n=>!home.includes(n)))}}})})}
function openServices(){const host=document.createElement("div");host.id="anp-custom-services-root";Object.assign(host.style,{position:"fixed",inset:"0",zIndex:"100000"});document.body.appendChild(host);const root=createRoot(host);root.render(<AllServices onClose={()=>{root.unmount();host.remove()}}/>)}
function AllServices({onClose}:{onClose:()=>void}){const home0=read(HOME_KEY,NAMES.slice(0,CAPACITY));const [home,setHome]=React.useState(home0);const [order,setOrder]=React.useState(()=>{const a=read(ALL_KEY,NAMES).filter(n=>!home0.includes(n));return [...a,...NAMES.filter(n=>!home0.includes(n)&&!a.includes(n))]});const add=(name:string)=>{if(home.length>=CAPACITY){toast("فضای صفحه اصلی پر است. یک خدمت را به همه خدمات منتقل کنید.");return}const next=[...home,name];setHome(next);write(HOME_KEY,next);setOrder(o=>o.filter(n=>n!==name));const b=findButton(name);if(b)b.style.display="";toast(`${name} به صفحه اصلی اضافه شد.`)};const reorder=(a:number,b:number)=>setOrder(o=>{const x=[...o],v=x.splice(a,1)[0];x.splice(b,0,v);write(ALL_KEY,x);return x});return <div className="anp-all-services" dir="rtl"><header><button onClick={onClose}>‹</button><div><b>همه خدمات</b><span>هیچ خدمتی حذف نمی‌شود.</span></div></header><div className="anp-home-drop">خدمت را با لمس طولانی به این قسمت بکشید تا به صفحه اصلی برگردد</div><main>{order.map((n,i)=><ServiceRow key={n} name={n} index={i} onReorder={reorder} onAdd={()=>add(n)}/>)}</main><style>{`.anp-all-services{min-height:100%;box-sizing:border-box;background:#020e18;color:#f4fafc;padding:calc(env(safe-area-inset-top) + 14px) 14px 24px;font-family:Vazirmatn,sans-serif}.anp-all-services header{display:flex;gap:12px;align-items:center;padding:6px 0 18px}.anp-all-services header>button{width:42px;height:42px;border:1px solid rgba(255,255,255,.08);border-radius:13px;background:#0b2230;color:#fff;font-size:29px}.anp-all-services header div{display:flex;flex-direction:column}.anp-all-services header b{font-size:20px}.anp-all-services header span{font-size:10px;color:#8ca0aa;margin-top:3px}.anp-home-drop{padding:11px;border:1px dashed rgba(0,214,176,.35);border-radius:14px;color:#8ca0aa;text-align:center;font:600 10px Vazirmatn;margin-bottom:11px}.anp-all-services main{display:grid;grid-template-columns:1fr 1fr;gap:10px}.anp-all-services main button{min-height:78px;border:1px solid rgba(255,255,255,.07);border-radius:17px;background:#071a24;color:#fff;padding:11px;display:flex;align-items:center;gap:8px;font:700 12px Vazirmatn}.anp-all-services main button.anp-dragging{transform:scale(.98);box-shadow:0 0 0 2px rgba(0,214,176,.32)}.anp-all-services i{width:34px;height:34px;border-radius:11px;background:rgba(0,214,176,.1);color:#00d6b0;display:grid;place-items:center;font-style:normal}.anp-all-services main span{flex:1;text-align:right}.anp-all-services em{color:#718892;font-style:normal;font-size:18px}`}</style></div>}
function ServiceRow({name,index,onReorder,onAdd}:{name:string;index:number;onReorder:(a:number,b:number)=>void;onAdd:()=>void}){const ref=React.useRef<HTMLButtonElement>(null);React.useEffect(()=>{if(ref.current)longPress(ref.current,{move:e=>{const bs=Array.from(document.querySelectorAll(".anp-all-services main button")) as HTMLElement[];const t=bs.find(x=>x!==ref.current&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(t){const to=bs.indexOf(t);if(to>=0)onReorder(index,to)}},drop:e=>{const r=document.querySelector(".anp-home-drop")?.getBoundingClientRect();if(r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)onAdd()})}},[index,onReorder,onAdd]);return <button ref={ref}><i>◉</i><span>{name}{name==="چک صیادی"&&<small>ثبت چک · استعلام چک‌های من</small>}</span><em>›</em></button>}
export function installServiceCustomization(){if(document.getElementById("anp-service-customization-style"))return;const style=document.createElement("style");style.id="anp-service-customization-style";style.textContent=".anp-drop-target{outline:2px solid #00d6b0!important;transform:scale(1.02)}.anp-dragging{box-shadow:0 0 0 2px rgba(0,214,176,.35)!important;opacity:.92}";document.head.appendChild(style);const obs=new MutationObserver(installHome);obs.observe(document.body,{childList:true,subtree:true});setTimeout(installHome,500);setTimeout(installHome,1500)}