const KEY="anp_home_services_v3";
const CAPACITY=16;
const NAMES=["موجودی کارت","انتقال وجه","شارژ مستقیم","بسته اینترنت","قبض","قبض‌ها","خدمات خودرو","خلافی خودرو","عوارض آزادراهی","طرح ترافیک تهران","بیمه","سامانه ثنا","قوه قضائیه","ثبت اسناد","نیکوکاری","تبدیل دلار تتر","صرافی","بازگشت وجه","شهریه پیام نور","چک صیادی","رتبه اعتباری من","عوارض شهرداری","تامین اجتماعی","صندوق رفاه وزارت بهداشت"];
const norm=(s:string)=>s.replace(/\s+/g," ").trim();
const label=(e:Element)=>norm((e as HTMLElement).innerText||e.getAttribute("aria-label")||e.getAttribute("title")||"");
const service=(e:HTMLElement)=>NAMES.find(n=>label(e)===n||label(e).startsWith(n+" "))||"";
type State={home?:string[];all?:string[]};
const read=():State=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return x&&typeof x==="object"?x as State:{}}catch{return {}}};
const write=(next:State)=>localStorage.setItem(KEY,JSON.stringify(next));
const saveHome=(home:string[])=>write({...read(),home:[...new Set(home.filter(Boolean))].slice(0,CAPACITY)});
const saveAll=(all:string[])=>write({...read(),all:[...new Set(all.filter(Boolean))]});
function toast(msg:string){document.getElementById("anp-svc-toast")?.remove();const e=document.createElement("div");e.id="anp-svc-toast";e.textContent=msg;e.dir="rtl";e.style.cssText="position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:100100;background:rgba(4,22,30,.97);color:#fff;border:1px solid rgba(0,214,176,.45);border-radius:14px;padding:10px 15px;font:700 12px Vazirmatn,sans-serif;box-shadow:0 8px 28px rgba(0,0,0,.35);pointer-events:none;white-space:nowrap";document.body.appendChild(e);setTimeout(()=>e.remove(),1600)}
function visibleServices(){return Array.from(document.querySelectorAll("button,[role='button']")).filter(e=>{const b=e as HTMLElement;return b.offsetParent!==null&&!!service(b)}) as HTMLElement[]}
function homeGroup(){const all=visibleServices();if(all.length<2)return null;const counts=new Map<HTMLElement,HTMLElement[]>();for(const b of all){const p=b.parentElement;if(!p)continue;const a=counts.get(p)||[];a.push(b);counts.set(p,a)}let best:[HTMLElement,HTMLElement[]]|null=null;for(const [p,a] of counts){if(!best||a.length>best[1].length)best=[p,a]}return best&&best[1].length>=2?{parent:best[0],items:best[1]}:null}
function disableLegacyDrag(el:HTMLElement){for(const k of ["onpointerdown","onpointermove","onpointerup","onpointercancel"])try{(el as any)[k]=null}catch{}}
function currentHome(g:{items:HTMLElement[]}){const r=read();const existing=g.items.map(service).filter(Boolean);let home=Array.isArray(r.home)?r.home.filter(n=>existing.includes(n)):[];if(!Array.isArray(r.home)){for(const n of existing)if(home.length<CAPACITY)home.push(n)}return [...new Set(home)].slice(0,CAPACITY)}
function persistOrder(g:{items:HTMLElement[]}){saveHome(g.items.map(service).filter(Boolean))}
function installHomeItem(el:HTMLElement,getGroup:()=>ReturnType<typeof homeGroup>){if(el.dataset.anpSvcV2)return;el.dataset.anpSvcV2="1";disableLegacyDrag(el);let timer=0;let drag=false;let moved=false;let sx=0,sy=0;const reset=()=>{clearTimeout(timer);drag=false;moved=false;el.classList.remove("anp-service-dragging")};el.addEventListener("pointerdown",e=>{sx=e.clientX;sy=e.clientY;moved=false;timer=window.setTimeout(()=>{drag=true;el.classList.add("anp-service-dragging");navigator.vibrate?.(18)},650)});el.addEventListener("pointermove",e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>12)moved=true;if(!drag||!moved)return;e.preventDefault();const all=document.getElementById("anp-all-services-button");if(all){const r=all.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){const n=service(el);const g=getGroup();if(g){el.style.display="none";persistOrder({items:g.items.filter(x=>x!==el)});toast(`${n} به همه خدمات منتقل شد.`)}reset();return}}const g=getGroup();if(!g)return;const target=g.items.find(x=>x!==el&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(target){g.parent.insertBefore(el,target);persistOrder({items:g.items)}}});el.addEventListener("pointerup",()=>{if(drag)persistOrder(getGroup()||{items:[]});reset()});el.addEventListener("pointercancel",reset);el.addEventListener("pointerleave",()=>{if(!drag)clearTimeout(timer)})}
function allServicesRoot(){return document.querySelector("[data-anp-all-services],.anp-all-services,#anp-all-services") as HTMLElement|null}
function installAllServiceItems(){const root=allServicesRoot();if(!root)return;const items=Array.from(root.querySelectorAll("button,[role='button']")).filter(e=>!!service(e as HTMLElement)) as HTMLElement[];if(!read().all?.length)saveAll(items.map(service).filter(Boolean));for(const el of items){if(el.dataset.anpSvcV2)return;el.dataset.anpSvcV2="1";let timer=0,drag=false,moved=false,sx=0,sy=0;el.addEventListener("pointerdown",e=>{sx=e.clientX;sy=e.clientY;moved=false;timer=window.setTimeout(()=>{drag=true;el.classList.add("anp-service-dragging");navigator.vibrate?.(18)},650)});el.addEventListener("pointermove",e=>{if(Math.hypot(e.clientX-sx,e.clientY-sy)>12)moved=true;if(!drag||!moved)return;e.preventDefault();const target=items.find(x=>x!==el&&(()=>{const r=x.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom})());if(target)root.insertBefore(el,target)});el.addEventListener("pointerup",e=>{clearTimeout(timer);if(!drag){drag=false;return}const homeButton=Array.from(root.querySelectorAll("button,[role='button']")).find(x=>/صفحه اصلی|بازگشت به خانه|خانه/.test(label(x))) as HTMLElement|null;if(homeButton&&homeButton!==el){const r=homeButton.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){const n=service(el);const g=homeGroup();const h=currentHome(g||{items:[]});if(h.includes(n)){toast(`${n} از قبل در صفحه اصلی است.`)}else if(h.length>=CAPACITY){toast("فضای صفحه اصلی پر است. یک خدمت را به همه خدمات منتقل کنید.")}else{saveHome([...h,n]);toast(`${n} به صفحه اصلی اضافه شد.`)}}}saveAll(Array.from(root.querySelectorAll("button,[role='button']")).map(x=>service(x as HTMLElement)).filter(Boolean));el.classList.remove("anp-service-dragging");drag=false;moved=false});el.addEventListener("pointercancel",()=>{clearTimeout(timer);el.classList.remove("anp-service-dragging");drag=false})}}
function apply(){const g=homeGroup();if(g){const r=read();const home=currentHome(g);const map=new Map(g.items.map(b=>[service(b),b]));home.forEach(n=>map.get(n)&&g.parent.appendChild(map.get(n)!));g.items.forEach(b=>{const n=service(b);b.style.display=home.includes(n)?"":"none";disableLegacyDrag(b);if(home.includes(n))installHomeItem(b,homeGroup)});if(!Array.isArray(r.home))saveHome(home)}installAllServiceItems()}
export function installServiceCustomizationV2(){if((document.body as any).dataset.anpSvcV2Installed)return;(document.body as any).dataset.anpSvcV2Installed="1";const style=document.createElement("style");style.textContent=".anp-service-dragging{outline:2px solid rgba(0,214,176,.7)!important;transform:scale(1.025);opacity:.84!important;z-index:100!important;box-shadow:0 8px 28px rgba(0,214,176,.2)!important}.anp-service-dragging *{pointer-events:none}";document.head.appendChild(style);const run=()=>apply();new MutationObserver(run).observe(document.body,{childList:true,subtree:true});setTimeout(run,400);setTimeout(run,1100)}
