import { BrowserMultiFormatReader } from "@zxing/browser";

const HINTS = ["بابت پرداخت قبض آب","بابت پرداخت قبض برق","بابت پرداخت قبض گاز","بابت پرداخت قبض تلفن","بابت پرداخت قبض اینترنت","بابت پرداخت قبض همراه اول","بابت پرداخت قبض ایرانسل","بابت پرداخت قبض"];
let activeOverlay: HTMLElement | null = null;

function isTransferPage() { return Array.from(document.querySelectorAll("h1,h2,h3,[role='heading']")).some(el => /انتقال\s*وجه/.test((el.textContent || "").trim())); }
function textOf(e: Element) { return ((e as HTMLElement).innerText || e.getAttribute("placeholder") || e.getAttribute("aria-label") || e.getAttribute("title") || "").replace(/\s+/g," ").trim(); }
function findText(s: string) { return Array.from(document.querySelectorAll("input,textarea,button,[role=button]")).find(e => textOf(e).includes(s)) as HTMLElement | null; }
function ensureStyles() {
  if (document.getElementById("anp-transfer-enhancement-styles")) return;
  const style = document.createElement("style"); style.id = "anp-transfer-enhancement-styles";
  style.textContent = `.app-content{padding-bottom:calc(64px + env(safe-area-inset-bottom,0px) + var(--anp-keyboard-inset,0px))!important}.anp-transfer-hints{margin-top:8px;padding:0 2px}.anp-hints-label{color:#7e929e;font-size:11px;font-weight:600;margin:0 0 7px}.anp-hints-list{display:flex;flex-wrap:wrap;gap:7px}.anp-hint-chip{border:1px solid rgba(0,214,176,.28);background:rgba(0,214,176,.08);color:#dffaf5;border-radius:999px;padding:8px 11px;font:600 11px Vazirmatn,sans-serif}.anp-hint-chip:active{transform:scale(.97);background:rgba(0,214,176,.16)}`;
  document.head.appendChild(style);
}
function scrollFieldIntoView(el: HTMLElement) { const run=()=>el.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"}); setTimeout(run,80); setTimeout(run,300); setTimeout(run,650); }
function installKeyboardScroll(el: HTMLInputElement | HTMLTextAreaElement) { if(el.dataset.anpKeyboardScroll)return; el.dataset.anpKeyboardScroll="1"; el.addEventListener("focus",()=>scrollFieldIntoView(el)); el.addEventListener("click",()=>scrollFieldIntoView(el)); }
function addDescriptionHints() {
  if(!isTransferPage())return;
  const el=Array.from(document.querySelectorAll("textarea,input")).find(x=>/توضیحات|شرح/.test(`${x.getAttribute("placeholder")||""}${x.getAttribute("aria-label")||""}`)) as HTMLInputElement|HTMLTextAreaElement|undefined;
  if(!el)return; installKeyboardScroll(el); let box=el.parentElement?.querySelector(".anp-transfer-hints") as HTMLElement|null;
  if(!box){box=document.createElement("div");box.className="anp-transfer-hints";el.parentElement?.appendChild(box)} if(el.dataset.anpHintsEvents)return; el.dataset.anpHintsEvents="1";
  const render=()=>{const q=(el.value||"").trim().replace(/\s+/g," ");const tokens=q.split(" ").filter(Boolean);const filtered=tokens.length?HINTS.filter(h=>tokens.every(t=>h.includes(t))).slice(0,5):HINTS.slice(0,4);box!.style.display=filtered.length?"block":"none";box!.innerHTML=filtered.length?`<div class="anp-hints-label">پیشنهاد توضیحات</div><div class="anp-hints-list">${filtered.map(t=>`<button type="button" class="anp-hint-chip">${t}</button>`).join("")}</div>`:"";box!.querySelectorAll<HTMLButtonElement>(".anp-hint-chip").forEach(b=>{b.addEventListener("pointerdown",e=>e.preventDefault());b.addEventListener("click",()=>{el.value=b.textContent||"";el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}));el.focus();scrollFieldIntoView(el)})})};
  el.addEventListener("input",render);el.addEventListener("focus",render);el.addEventListener("blur",()=>setTimeout(()=>{if(!box!.contains(document.activeElement))box!.style.display="none"},180));render();
}
function setInputValue(input: HTMLInputElement | HTMLTextAreaElement,value:string){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input),"value")?.set;if(setter)setter.call(input,value);else input.value=value;input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));input.focus();}
function closeScanner(){activeOverlay?.querySelectorAll("video").forEach(v=>{const s=(v as HTMLVideoElement).srcObject as MediaStream|null;s?.getTracks().forEach(t=>t.stop())});activeOverlay?.remove();activeOverlay=null;}
function openCardScanner(){
  closeScanner();
  const target=(findText("کارت مقصد")||findText("شماره کارت مقصد")||findText("شماره کارت")) as HTMLInputElement|null; if(!target)return;
  const overlay=document.createElement("div"); overlay.dir="rtl"; overlay.style.cssText="position:fixed;inset:0;z-index:100004;background:#020e18;color:#fff;font-family:Vazirmatn,sans-serif;display:flex;flex-direction:column;align-items:center;overflow:hidden";
  overlay.innerHTML=`<div style="width:100%;display:flex;align-items:center;justify-content:space-between;padding:calc(env(safe-area-inset-top,0px) + 14px) 16px 12px;box-sizing:border-box;background:rgba(0,0,0,.28);border-bottom:1px solid rgba(0,214,176,.12)"><button data-close style="border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);color:#fff;border-radius:12px;padding:9px 16px;font:700 13px Vazirmatn">بستن</button><b style="font-size:15px">اپلیکیشن آن پرداز</b><span style="width:52px"></span></div><div style="margin-top:34px;text-align:center;padding:0 22px"><strong style="display:block;font-size:19px">اسکن بارکد کارت مقصد</strong><span style="display:block;color:rgba(255,255,255,.58);font-size:12px;margin-top:7px">بارکد کارت مقصد را داخل کادر قرار دهید</span></div><div style="position:relative;width:min(76vw,300px);aspect-ratio:1;margin-top:28px;border:2px solid #00d6b0;border-radius:22px;overflow:hidden;background:#000;box-shadow:0 0 42px rgba(0,214,176,.15)"><video data-video autoplay playsinline muted style="width:100%;height:100%;object-fit:cover;display:block"></video><div style="position:absolute;inset:18px;border:2px solid rgba(0,214,176,.85);border-radius:15px;pointer-events:none"></div><div style="position:absolute;left:12%;right:12%;top:50%;height:2px;background:#00d6b0;box-shadow:0 0 12px #00d6b0;animation:anpScanLine 1.35s ease-in-out infinite"></div></div><p data-status style="color:rgba(255,255,255,.58);font-size:12px;margin:20px 24px;text-align:center;line-height:1.8">در حال فعال‌سازی دوربین...</p>`;
  const style=document.createElement("style");style.textContent="@keyframes anpScanLine{0%,100%{transform:translateY(-72px);opacity:.35}50%{transform:translateY(72px);opacity:1}}";overlay.appendChild(style);document.body.appendChild(overlay);activeOverlay=overlay;overlay.querySelector<HTMLButtonElement>("[data-close]")!.onclick=closeScanner;
  const video=overlay.querySelector<HTMLVideoElement>("[data-video]")!;const status=overlay.querySelector<HTMLElement>("[data-status]")!;const reader=new BrowserMultiFormatReader();let controls:{stop:()=>void}|undefined;let finished=false;
  reader.decodeFromConstraints({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}}},video,(result)=>{if(!result||finished)return;const raw=result.getText();const clean=raw.replace(/\D/g,"").slice(0,16);if(clean.length!==16){status.textContent="بارکد شناسایی شد اما شماره کارت ۱۶ رقمی نیست.";return}finished=true;controls?.stop();setInputValue(target,clean);status.textContent="شماره کارت مقصد وارد شد.";setTimeout(closeScanner,350)}).then(c=>{controls=c;status.textContent="دوربین فعال است؛ بارکد کارت مقصد را داخل کادر قرار دهید."}).catch(()=>{status.textContent="دسترسی به دوربین ممکن نشد. مجوز دوربین را فعال کنید و دوباره تلاش کنید."});
}
function addScanner(){if(!isTransferPage())return;const target=findText("کارت مقصد")||findText("شماره کارت مقصد")||findText("شماره کارت");if(!target||target.dataset.anpScanner)return;target.dataset.anpScanner="1";const wrap=document.createElement("div");wrap.style.cssText="display:flex;align-items:center;gap:8px;margin-top:7px";const b=document.createElement("button");b.type="button";b.textContent="▣";b.setAttribute("aria-label","اسکن بارکد کارت مقصد");b.title="اسکن بارکد کارت مقصد";b.style.cssText="width:42px;height:42px;min-width:42px;padding:0;border:1px solid rgba(0,214,176,.38);border-radius:11px;background:rgba(0,214,176,.08);color:#00d6b0;font:700 19px Vazirmatn,sans-serif;display:flex;align-items:center;justify-content:center";b.onclick=openCardScanner;wrap.appendChild(b);target.parentElement?.appendChild(wrap);}
export function installTransferEnhancements(){ensureStyles();let queued=false;const run=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;if(isTransferPage()){addDescriptionHints();addScanner()}})};new MutationObserver(run).observe(document.body,{childList:true,subtree:true});setTimeout(run,350);setTimeout(run,1000);}
