import { createRoot, type Root } from "react-dom/client";
const HINTS=["بابت خرید","بابت اجاره","بابت قرض","بابت هزینه خدمات","بابت هدیه","بابت تسویه حساب","بابت هزینه شخصی"];
let scanRoot:Root|null=null;
function findText(s:string){return Array.from(document.querySelectorAll("input,textarea,button,[role=button]")).find(e=>((e as HTMLElement).innerText||e.getAttribute("placeholder")||e.getAttribute("aria-label")||"").includes(s)) as HTMLElement|null}
function addDescriptionHints(){const el=Array.from(document.querySelectorAll("textarea,input")).find(x=>/توضیحات|شرح/.test((x.getAttribute("placeholder")||"")+(x.getAttribute("aria-label")||""))) as HTMLInputElement|HTMLTextAreaElement|null;if(!el||el.dataset.anpHints)return;el.dataset.anpHints="1";const box=document.createElement("div");box.className="anp-transfer-hints";box.innerHTML=`<small>توضیحات اختیاری است؛ ننوشتن توضیحات ممکن است باعث دشواری در شناسایی علت و مقصد تراکنش و پیگیری آن شود.</small><div>${HINTS.map(x=>`<button type="button">${x}</button>`).join("")}</div>`;el.parentElement?.appendChild(box);box.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{el.value=(el.value?el.value+" ":"")+b.textContent;el.dispatchEvent(new Event("input",{bubbles:true}));el.focus()}));}
function ScannerOverlay({onClose}:{onClose:()=>void}){return <div dir="rtl" style={{position:"fixed",inset:0,zIndex:100001,background:"#020e18",color:"white",fontFamily:"Vazirmatn,sans-serif",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}><b style={{fontSize:22,marginBottom:8}}>آن پرداز</b><strong style={{fontSize:17}}>بارکد حساب بانکی مقصد را اسکن کنید</strong><div style={{width:"min(78vw,330px)",aspectRatio:"1",border:"2px solid #00d6b0",borderRadius:28,margin:"28px 0",boxShadow:"0 0 45px rgba(0,214,176,.18)"}}/><button onClick={onClose} style={{padding:"12px 28px",border:0,borderRadius:14,background:"#12303b",color:"white",fontFamily:"inherit"}}>انصراف</button></div>}
async function scan(){const host=document.createElement("div");host.id="anp-scanner-overlay";document.body.appendChild(host);scanRoot=createRoot(host);scanRoot.render(<ScannerOverlay onClose={()=>{scanRoot?.unmount();host.remove();scanRoot=null}}/>);try{const stream=await navigator.mediaDevices?.getUserMedia({video:{facingMode:{ideal:"environment"}}});if(stream){const video=document.createElement("video");video.srcObject=stream;video.autoplay=true;video.playsInline=true;video.style.cssText="position:fixed;inset:0;width:100%;height:100%;object-fit:cover;z-index:-1";host.appendChild(video);}}catch{}}
function addScanner(){const target=findText("کارت مقصد")||findText("شماره کارت مقصد")||findText("شماره کارت");if(!target||target.dataset.anpScanner)return;target.dataset.anpScanner="1";const b=document.createElement("button");b.type="button";b.textContent="▣ اسکن";b.setAttribute("aria-label","اسکن بارکد حساب مقصد");b.style.cssText="margin:7px 0;border:1px solid rgba(0,214,176,.35);border-radius:12px;background:rgba(0,214,176,.08);color:#00d6b0;padding:9px 13px;font:700 12px Vazirmatn,sans-serif";b.onclick=scan;target.parentElement?.appendChild(b)}
export function installTransferEnhancements(){const run=()=>{addDescriptionHints();addScanner()};const o=new MutationObserver(run);o.observe(document.body,{childList:true,subtree:true});setTimeout(run,500);}
