import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const replacements = [
  { file: 'src/index.css', from: /^@import url\('https:\/\/fonts\.googleapis\.com\/css2\?family=Vazirmatn:[^\n]+\);\n?/m, to: '' },
  { file: 'src/App.tsx', from: '},2200);return()=>clearTimeout(t)},[]);', to: '},900);return()=>clearTimeout(t)},[]);' },
  { file: 'src/App.tsx', from: 'setTimeout(()=>setHomeSkeleton(false),5000)', to: 'setTimeout(()=>setHomeSkeleton(false),600)' },
  { file: 'src/App.tsx', from: 'useEffect(()=>{fetchUSDTRate().then(r=>{setRate(r);setRateLoading(false)});const iv=setInterval(()=>fetchUSDTRate().then(setRate),60000);return()=>clearInterval(iv)},[]);', to: 'useEffect(()=>{let cancelled=false;const loadRate=()=>fetchUSDTRate().then(r=>{if(!cancelled){setRate(r);setRateLoading(false)}});const first=window.setTimeout(loadRate,1200);const iv=window.setInterval(loadRate,60000);return()=>{cancelled=true;window.clearTimeout(first);window.clearInterval(iv)}},[]);' },
  { file: 'src/App.tsx', from: 'interface ExOrder {\n  id: string; pair: string; side: "buy" | "sell";\n  price: number; amount: number; total: number;\n  status: "open" | "filled" | "cancelled"; createdAt: string;\n  mode?: "spot" | "margin";\n}', to: 'interface ExOrder {\n  id: string; pair: string; side: "buy" | "sell";\n  price: number; amount: number; total: number;\n  status: "open" | "filled" | "cancelled"; createdAt: string;\n  mode?: "spot" | "margin";\n  orderType?: "market" | "limit" | "stop";\n  triggerPrice?: number;\n}' },
  { file: 'src/App.tsx', from: 'const pnl=pos.side==="long"?(currentPrice-pos.entry)*pos.qty*pos.leverage:(pos.entry-currentPrice)*pos.qty*pos.leverage;', to: 'const pnl=pos.side==="long"?(currentPrice-pos.entry)*pos.qty:(pos.entry-currentPrice)*pos.qty;' },
  { file: 'src/App.tsx', from: 'const pnl=pos.side==="long"?(c.price-pos.entry)*pos.qty*pos.leverage:(pos.entry-c.price)*pos.qty*pos.leverage;', to: 'const pnl=pos.side==="long"?(c.price-pos.entry)*pos.qty:(pos.entry-c.price)*pos.qty;' },
  { file: 'src/App.tsx', from: 'const updW={...wallet,toman:buy?Math.max(0,newToman-total-fee):newToman+total-fee};DB.saveExWallet(updW);const newPos', to: 'const updW={...wallet,toman:buy?Math.max(0,newToman-margin-fee):newToman+margin-fee};DB.saveExWallet(updW);const newPos' },
  { file: 'src/App.tsx', from: 'const next={...user,tomanBalance:user.tomanBalance-total-fee};', to: 'const next={...user,tomanBalance:Math.max(0,user.tomanBalance-margin-fee)};' },
  { file: 'src/App.tsx', from: 'const [orderSide,setOrderSide]=useState<"buy"|"sell"|null>(null),[orderType,setOrderType]=useState("قیمت بازار"),[orderAmount,setOrderAmount]=useState("")', to: 'const [orderSide,setOrderSide]=useState<"buy"|"sell"|null>(null),[orderType,setOrderType]=useState("قیمت بازار"),[orderAmount,setOrderAmount]=useState(""),[orderPrice,setOrderPrice]=useState("")' },
  { file: 'src/App.tsx', from: 'const closeOrder=()=>{setOrderSide(null);setOrderAmount("")};', to: 'const closeOrder=()=>{setOrderSide(null);setOrderAmount("");setOrderPrice("")};' },
  { file: 'src/App.tsx', from: 'const total=quantity*coin.price;setProcessing(true);', to: 'const executionPrice=orderType==="قیمت بازار"?coin.price:(Number(toLatinDigits(orderPrice))||coin.price);const total=quantity*executionPrice;setProcessing(true);' },
  { file: 'src/App.tsx', from: 'note:`معامله نمودار · ${buying?"خرید":"فروش"} ${asset}/TMN · ${orderType} · قیمت ${Math.round(coin.price)}`', to: 'note:`معامله نمودار · ${buying?"خرید":"فروش"} ${asset}/TMN · ${orderType} · قیمت ${Math.round(executionPrice)}`' },
  { file: 'src/App.tsx', from: '<input inputMode="decimal" placeholder={fa(Math.round(coin.price)}/>', to: '<input inputMode="decimal" value={toFaDigits(orderPrice)} onChange={e=>setOrderPrice(toLatinDigits(e.target.value).replace(/[^0-9.]/g,""))} placeholder={fa(Math.round(coin.price))}/>' },
  { file: 'src/App.tsx', from: '<input inputMode="decimal" placeholder={fa(Math.round(coin.price))}/>', to: '<input inputMode="decimal" value={toFaDigits(orderPrice)} onChange={e=>setOrderPrice(toLatinDigits(e.target.value).replace(/[^0-9.]/g,""))} placeholder={fa(Math.round(coin.price))}/>' },
  // A stop order is kept open until the market reaches its trigger price.
  { file: 'src/App.tsx', from: 'const executionPrice=orderType==="قیمت بازار"?coin.price:(Number(toLatinDigits(orderPrice))||coin.price);const total=quantity*executionPrice;setProcessing(true);', to: 'const executionPrice=orderType==="قیمت بازار"?coin.price:(Number(toLatinDigits(orderPrice))||coin.price);const total=quantity*executionPrice;if(orderType==="حد ضرر"){const trigger=Number(toLatinDigits(orderPrice));if(!trigger||!quantity)return;const stopOrder:ExOrder={id:genId(),pair:`${asset}/TOMAN`,side:orderSide!,price:0,amount:quantity,total:trigger*quantity,status:"open",createdAt:new Date().toISOString(),mode:"spot",orderType:"stop",triggerPrice:trigger};DB.saveExOrders([stopOrder,...DB.getExOrders()]);setProcessing(false);closeOrder();setReceipt({title:"سفارش حد ضرر ثبت شد",amount:`${faFixed(quantity,4)} ${asset}`,destination:`فعال‌سازی در ${fa(Math.round(trigger))} تومان`,detail:"سفارش تا رسیدن قیمت به حد فعال‌سازی باز می‌ماند."});return;}setProcessing(true);' },
  // Make limit/stop spot orders persistent and trigger them against the current market price.
  { file: 'src/App.tsx', from: 'const toggleFavorite=()=>onToggleFavorite(asset);const place=()=>qty&&setConfirm(true);', to: 'useEffect(()=>{if(mode!=="spot")return;const market=coin.price;const all=DB.getExOrders();let changed=false;const next=all.map(o=>{if(o.mode!=="spot"||o.status!=="open")return o;const [base,quote]=o.pair.split("/");if(base!==asset)return o;const trigger=o.orderType==="stop"?(o.triggerPrice??o.price):o.price;const hit=o.orderType==="stop"?(o.side==="buy"?market>=trigger:market<=trigger):(o.side==="buy"?market<=trigger:market>=trigger);if(!hit)return o;const wallet=DB.getExWallet();const baseBal=(wallet as Record<string,number>)[base]??0;const quoteKey=quote==="TOMAN"?"toman":"USDT";const quoteBal=(wallet as Record<string,number>)[quoteKey]??0;const fillTotal=market*o.amount;const fillFee=fillTotal*.003;if(o.side==="buy"&&quoteBal<fillTotal+fillFee)return o;if(o.side==="sell"&&baseBal<o.amount)return o;const updatedWallet={...wallet,[base]:o.side==="buy"?baseBal+o.amount:Math.max(0,baseBal-o.amount),[quoteKey]:o.side==="buy"?Math.max(0,quoteBal-fillTotal-fillFee):quoteBal+fillTotal-fillFee};DB.saveExWallet(updatedWallet);changed=true;return {...o,status:"filled",price:market,total:fillTotal};});if(changed){DB.saveExOrders(next);setOrders(next);}},[tick,coin.price,asset,mode]);const toggleFavorite=()=>onToggleFavorite(asset);const place=()=>qty&&setConfirm(true);' },
  // Orders already stored by older builds without orderType are treated as limit orders.
];

for (const item of replacements) {
  if (!existsSync(item.file)) continue;
  const original = readFileSync(item.file, 'utf8');
  const updated = original.replace(item.from, item.to);
  if (updated !== original) writeFileSync(item.file, updated);
}
